name: Docker - Deploy Release 

on:
  push:
    tags:
    - '*'
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5
      - name: Build Docker Image
        uses: docker/build-push-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: atomizer/test-agent
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
